name: Build test-f
permissions:
  packages: write
on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/build-test-f.yml"
      - "test-ffmpeg/"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./test-ffmpeg/
          push: true
          tags: ghcr.io/maa123/build-images/test-ffmpeg:latest
          cache-from: type=gha,scope=test-ffmpeg
          cache-to: type=gha,mode=max,scope=test-ffmpeg
