name: Build mirak
permissions:
  packages: write
on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/build-mirak.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: clone
        run: git clone https://github.com/mirakc/mirakc.git --depth=1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./docker/Dockerfile.alpine
          target: mirakc
          push: true
          tags: ghcr.io/maa123/build-images/mirakc:latest
          cache-from: type=gha,scope=mirak
          cache-to: type=gha,mode=max,scope=mirak
