name: Build Test Mac
permissions:
  packages: write
on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/build-test-mac.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: setup Docker
        run: brew install docker colima
      - uses: actions/checkout@v4
      - name: clone
        run: git clone https://github.com/cloudflare/cloudflared.git --depth=1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./cloudflared/
          push: true
          tags: ghcr.io/maa123/build-images/test-mac:latest,ghcr.io/maa123/build-images/test-mac:${{ github.sha }}
          cache-from: type=gha,scope=test-mac
          cache-to: type=gha,mode=max,scope=test-mac
